/*
 * Copyright (c) 2007-2018, Marketo, Inc. All rights reserved.
 * See https://developers.marketo.com/MunchkinLicense.pdf for license terms
 * Marketo marketing automation web activity tracking script
 * Version: 158 r780
 */
 (function(h){if(!h.MunchkinTracker){var l=h.document,q=l.location,D=encodeURIComponent,A=!1,u=null,s=null,E=!1,x=null,F=[],v=function(b,a,c,d){try{var e=function(){try{c.apply(this,arguments)}catch(a){}};b.addEventListener?b.addEventListener(a,e,d||!1):b.attachEvent&&b.attachEvent("on"+a,e);F.push([b,a,e,d])}catch(k){}},V=function(b,a,c,d){try{b.removeEventListener?b.removeEventListener(a,c,d||!1):b.detachEvent&&b.detachEvent("on"+a,c)}catch(e){}},e=function(b){return"undefined"!==typeof b&&null!==
b},G=function(b,a){return b.className.match(RegExp("(\\s|^)"+a+"(\\s|$)"))},W=e(h.XMLHttpRequest)&&e((new h.XMLHttpRequest).withCredentials),t=function(b){var a=null,c;if(e(b))if(0===b.length)a="";else try{a=decodeURIComponent(b)}catch(d){c=b.indexOf("?");if(-1!==c)try{a=decodeURIComponent(b.substr(0,c))+b.substr(c)}catch(g){}e(a)||(a=String(b))}return a},H=function(b,a){var c={},d=e(a)?a:"=",g=b.split("&"),k=g.length,f,n,l;for(f=0;f<k;f+=1)n=g[f].split(d),e(n)&&1<n.length&&(l=n.shift(),n=n.join(d),
c[t(l)]=t(n));return c},I=function(b){try{var a=l.createElement("a");a.href=b;return H(a.search.substr(1))}catch(c){return null}},J=function(b,a){var c=null,d=[];if(e(b))for(c in b)b.hasOwnProperty(c)&&"function"!==typeof b[c]&&null!==b[c]&&d.push(D(c)+(e(a)?a:"=")+D(b[c]));return d.join("&")},K=function(b,a){var c=null;if(e(a)&&e(b))for(c in b)b.hasOwnProperty(c)&&e(a[c])&&(b[c]=a[c])},L=function(b,a,c){var d=b.split("."),g=d.length,f=2;if(e(a))f=a;else if(e(c)&&c)"com"!==d[g-1]&&(a=RegExp("^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])$"),
4===g&&a.test(b)?f=4:2===d[g-1].length&&1<g&&"co"===d[g-2]&&(f=3));else if(2<d[g-1].length)f=2;else if(2===d[g-1].length)f=3;else return b;for(;d.length>f&&2<d.length;)d.shift();return d.join(".")},y=function(b){var a=l.cookie,c,d,g={id:null,token:null};b=D(b);g.store=function(a,c,d,e){var g=b+"="+J(this,":"),f=new Date;0<a?f.setTime(f.getTime()+864E5*a):f.setTime(f.getTime()-1);g+="; expires="+f.toGMTString();c&&(g+="; path="+c);d&&-1!==d.indexOf(".")&&(g+="; domain="+d);e&&(g+="; secure");l.cookie=
g};if(""!==a)for(a=a.split(";"),c=0;c<a.length;c+=1)if(d=a[c].replace(/^\s+|\s+$/g,""),0===d.indexOf(b+"=")){a=d.substring(b.length+1);c=H(a);e(c.id)&&e(c.token)?K(g,c):K(g,H(a,":"));break}return g},f={customName:null,notifyPrefix:null,wsInfo:null,altIds:[],visitorToken:null,cookieLifeDays:730,clickTime:350,cookieAnon:!0,mkt_tok:null,domainLevel:null,domainSelectorV2:!0,replayDetectLimit:5E3,httpsOnly:!1,asyncOnly:!1,anonymizeIP:!1,apiOnly:!1,externalSource:null,orgId:null,_ecid:null,_itpMitigationForAll:!1},
m=null,p=null,X=h.navigator.cookieEnabled||l.hasOwnProperty("cookie")&&(0<l.cookie.length||-1<(l.cookie="testcookie=test; max-age=10000").indexOf.call(l.cookie,"testcookie=test;")),B=!1,C=[],M=null,Y=function(b,a,c){var d=new h.XMLHttpRequest;d.open("GET",b,!0!==a);d.onreadystatechange=function(){2<=d.readyState&&d.abort()};if(a)try{d.timeout=c}catch(e){}try{d.send()}catch(f){}},Q=function(b,a,c,d,e){b=b+a+"&"+J(c)+"&"+J(d);c=(new Date).getTime();e=!e&&!f.asyncOnly;0===a.indexOf("webevents/visitWebPage?")&&
(e=!1);W?Y(b,e,f.clickTime):(new h.Image(1,1)).src=b;M=c+f.clickTime},Z=function(){var b;return function(a,c){var d={x:a.clientX,y:a.clientY,el:c,time:(new Date).getTime()};if(e(b)&&d.x===b.x&&d.y===b.y&&d.el===b.el&&d.time<b.time+f.replayDetectLimit)return!0;b=d;return!1}}(),R=function(){var b=l.getElementsByName("_mkt_trk"),a=0,c="";e(p)&&(c="id:"+p.id+"&token:"+p.token);for(a=0;a<b.length;a+=1)"hidden"===b[a].type&&(b[a].value=c)},w=function(b,a,c,d){var g=null,k;k=q.hostname;var l=q.protocol,
n="webevents/"+b;if(B){var h;if(h=window.navigator)a:{h=window.navigator.userAgent;if("string"===typeof h&&h){if(0<=h.indexOf("AdsBot")||0<=h.indexOf("Wget")||0<=h.indexOf("msnbot")){h=!0;break a}if(0<=h.indexOf("Mozilla")&&(0<=h.indexOf("slurp")||0<=h.indexOf("bot"))){h=!0;break a}}h=!1}if(!h&&e(p)&&(a._mchId=p.id,a._mchTk=p.token,e(f.mkt_tok)&&(a.mkt_tok=f.mkt_tok),e(f.wsInfo)&&(a._mchWs=f.wsInfo),"clickLink"===b&&(a._mchCn=e(f.customName)?f.customName:""),a._mchHo=k,a._mchPo=q.port,e(a._mchRu)||
(a._mchRu=t(q.pathname)),a._mchPc=l,a._mchVr="158",e(k)&&0!==k.length&&"file:"!==l))for(g in f.anonymizeIP&&(a.aip=1),e(f.externalSource)&&(a._mchEs=f.externalSource),e(x)&&(a._mchEcid=x),n+="?_mchNc="+(new Date).getTime(),Q(f.notifyPrefix,n,a,c,d),f.altIds)f.altIds.hasOwnProperty(g)&&(k=f.altIds[g],a._mchId=k,Q(f.notifyPrefix.replace(/\w{3}\-\w{3}\-\w{3}\.mktoresp\.com/i,k+".mktoresp.com"),n,a,c,d))}else C.push(["post",arguments])},S=function(b){var a=b||h.event,c=a.target||a.srcElement,d={},f;f=
a.which;var k=a.button;f=e(f)&&(1===f||2===f)||e(k)&&(0===k||1===k||4===k)?!0:!1;if(f&&!a._mchDone){a._mchDone=!0;a=c;f=q.href||q;for(-1<f.indexOf("#")&&(f=f.substring(0,f.indexOf("#")));"A"!==a.tagName&&"AREA"!==a.tagName&&e(a.parentNode);)a=a.parentNode;a===l||a===h||"A"!==a.tagName&&"AREA"!==a.tagName?a=null:(c=a.href.replace(/^\s+|\s+$/g,""),a=e(c)&&0<c.length&&0!==c.indexOf("#")&&0!==c.indexOf(f+"#")&&0!==c.indexOf("javascript")&&0!==c.indexOf("mailto")&&!G(a,"mchNoDecorate")?a:null);e(a)&&!Z(b,
a)&&(d._mchHr=t(a.href),w("clickLink",d))}},z=function(b){if(B){if(null!==p)return p;var a=L(q.hostname,f.domainLevel,f.domainSelectorV2),c=y("_mkto_trk"),d=!1!==f.httpsOnly;if(e(c.id)||f.cookieAnon||b){if(c.id=m,e(c.token)||(e(f.visitorToken)&&"VISITOR_MKTTOK_REPLACE"!==f.visitorToken?c.token=f.visitorToken:c.token="_mch-"+a+"-"+(new Date).getTime()+"-"+(Math.floor(9E4*Math.random())+1E4)),c.store(f.cookieLifeDays,"/",a,d),d&&(c=y("_mkto_trk")),!d||e(c.id))return p=c,R(),c}else return null}else C.push(["createTrackingCookie",
arguments])},T=function(){z(!0)},$=function(b){var a=b.onclick;b.onclick="function"===typeof a?function(){T.apply(b,arguments);return a.apply(b,arguments)}:T},N=function(b){var a=L(q.hostname,f.domainLevel,f.domainSelectorV2),c=y("mkto_opt_out"),d=!1!==f.httpsOnly;b?(c.id=!0,c.store(730,"/",a,d),b=y("_mkto_trk"),b.id&&b.store(0,"/",a,d)):c.store(0,"/",a,d)},U=function(){A&&e(s)&&E?window.fetch("https://"+s+"/getCookie?_mchId="+m+"&_mchTd="+u,{credentials:"include"}).then(function(b){if(b.ok)return b.body;
throw Error("status ${response.status}");})["catch"](function(b){window.console.warn("getCookie failed - ",b);window.localStorage.removeItem("_mktoLpDomain_"+m+"_"+u);window.localStorage.removeItem("_mktoSecureLp_"+m);s=null})["finally"](O):O()},O=function(){if(!B){B=!0;var b=z(e(f.mkt_tok)),a,c;c={};for(var d={};0<C.length;)switch(a=C.shift(),a[0]){case "createTrackingCookie":b=z.apply(l,a[1]);break;case "post":w.apply(l,a[1])}if(e(f._ecid))x=f._ecid;else a:{a=f.orgId;if(e(window.Visitor)&&e(a))try{var g=
window.Visitor.getInstance(a);if(e(g)){x=a+":"+g.getLocationHint()+":"+g.getMarketingCloudVisitorID();break a}}catch(k){}for(var g=RegExp("AMCV_([A-Za-z0-9]+%40AdobeOrg)=([^;]+)","g"),m,n=[];null!==(m=g.exec(l.cookie));){var p=decodeURIComponent(m[1]),r;e(a)&&p!==a||null===(r=/MCMID%7C([^%]+)/.exec(m[2]))||(m=/MCAAMLH-[^%]+%7C([0-9]+)/.exec(m[2]),n.push(p+":"+(e(m)?m[1]:"")+":"+r[1]))}x=n.join(";")}if(e(b))f.apiOnly||(c._mchCn=e(f.customName)?f.customName:"",d._mchHa=t(q.hash),d._mchRe=t(l.referrer),
d._mchQp=t(q.search.substr(1).replace(/&/g,"__-__")),w("visitWebPage",c,d,!0));else if(!(f.cookieAnon||e(h.Mkto)&&e(h.Mkto.formSubmit))){b=[];c=l.forms;d=c.length;for(r=0;r<d;r+=1)if(G(c[r],"lpeRegForm"))for(g=c[r].elements,n=g.length,a=0;a<n;a+=1)"submit"!==g[a].type||G(g[a],"mchNoDecorate")||b.push(g[a]);for(c=0;c<b.length;c+=1)$(b[c])}}},P={ASSOCIATE_LEAD:"associateLead",CLICK_LINK:"clickLink",VISIT_WEB_PAGE:"visitWebPage",init:function(b,a){if(X&&e(b)&&0!==b.length){m=b;m=m.toUpperCase();var c=
"",d,g,k;d=I(h.location.toString());var p=null;f.notifyPrefix=q.protocol+"//"+m+".mktoresp.com/";e(a)&&(window.console.debug('Munchkin.init("%s") options:',b,a),K(f,a));e(d)&&(e(d.mkt_tok)&&(f.mkt_tok=d.mkt_tok),e(d.lpview)&&(c=d.lpview),e(d.marketo_opt_out)&&(p=d.marketo_opt_out));if(!e(f.mkt_tok))if(d=I(l.referrer),e(d.mkt_tok))f.mkt_tok=d.mkt_tok;else if(e(d.enid)&&e(d.type))for(k in d)d.hasOwnProperty(k)&&"enid"!==k&&"type"!==k&&(-1<k.indexOf("mkt_tok")||-1<d[k].indexOf("mkt_tok"))&&(g=I(k+"="+
d[k]),e(g.mkt_tok)&&(f.mkt_tok=g.mkt_tok));if("preview"!==c||!/\/lpeditor\/preview$/.test(q.pathname)){if(null===p){if(c=y("mkto_opt_out"),e(c.id)){N(!0);return}}else{if("true"===p){N(!0);return}"false"===p&&N(!1)}k=window.navigator.userAgent.toLowerCase();c=-1<k.indexOf("safari");k=/ version\/([0-9]+.[0-9]+)/.exec(k);A=c&&k&&12.1<=parseFloat(k[1])||f._itpMitigationForAll;u=L(q.hostname,f.domainLevel,f.domainSelectorV2);s=window.localStorage.getItem("_mktoLpDomain_"+m+"_"+u);e(s)&&-1<l.cookie.indexOf("_mkto_trk=")&&
(A=!1);A&&window.fetch?(E="true"===window.localStorage.getItem("_mktoSecureLp_"+m),e(s)?U():window.fetch(q.protocol+"//"+m+".mktoutil.com/mktoutil/lpDomain?_mchId="+m+"&_mchTd="+u).then(function(a){if(a.ok)return a.json();throw Error("status ${response.status}");})["catch"](function(a){window.console.warn("getLpDomain failed - ",a)}).then(function(a){e(a)&&e(a.domain)&&(window.localStorage.setItem("_mktoLpDomain_"+m+"_"+u,s=a.domain),window.localStorage.setItem("_mktoSecureLp_"+m,E=a.isSecure))})["finally"](U)):
O()}}},munchkinFunction:function(b,a,c){var d={},f={},k=null;e(c)&&(d._mchKy=c);switch(b){case "associateLead":for(k in a)a.hasOwnProperty(k)&&(d["_mchAt"+k]=a[k]);z(!0);w("associateLead",d);break;case "clickLink":e(a.href)&&(d._mchHr=d._mchLr=a.href,w("clickLink",d));break;case "visitWebPage":e(a.url)&&(d._mchRu=a.url),e(a.params)&&(d._mchQp=a.params),e(a.name)&&(d._mchCn=a.name),f._mchRe=q.referrer,w("visitWebPage",d,f)}},createTrackingCookie:function(b){z(b)}};Date.prototype.getTimeAlias=Date.prototype.getTime;
v(h,"beforeunload",function(){for(var b;0<F.length;)b=F.shift(),V.apply(this,b);if(e(M)){do b=new Date;while(b.getTimeAlias()<M)}});v(l,"click",S,!0);(function(b){var a=!1,c=!0,d=l.documentElement,e=function(c){"readystatechange"===c.type&&"complete"!==l.readyState||a||(a=!0,b.call(h,c.type||c))},f=null,f=function(){try{d.doScroll("left")}catch(a){h.setTimeout(f,50);return}e("poll")};if("complete"===l.readyState)b.call(h,"lazy");else{if(l.createEventObject&&d.doScroll){try{c=!h.frameElement}catch(m){}c&&
f()}v(l,"DOMContentLoaded",e);v(l,"readystatechange",e);v(h,"load",e)}})(function(){R();var b=0;if(e(l.links))for(b=0;b<l.links.length;b+=1)v(l.links[b],"click",S,!0)});h.MunchkinTracker=h.Munchkin=P;h.mktoMunchkin=P.init;h.mktoMunchkinFunction=P.munchkinFunction}})(window);
